name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src

      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version-file: "src/package.json"

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Build
        run: npm run build
        working-directory: src

      - name: Deploy
        run: |
          mkdir dist
          cp -r src/wwwroot dist

          cd dist
          git init
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add .
          git commit -m "Deployment"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages